### ISSUE TITLE
Twind completions in Fresh (Deno) workspace not autocompleting custom theme

### ISSUE THREAD

**Issue by imjamesb** [tw-in-js/vscode-twind-intellisense#18] opened 2022-09-26 00:34 UTC
twind config

```ts
// /twind.config.ts
export default {
  selfURL: import.meta.url,
  darkMode: "class",
  mode: "silent",
  theme: {
    "colors": {
      "transparent": "transparent",
      "inherit": "inherit",
      "black": "black",
      "white": "white",
      // ...
      "yellow-A700": "#FFD600",
    },
    "fontFamily": {
      "sans":
        '"Inter var", "ui-sans-serif", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Nueue", "Arial", "Nato Sans", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Nato Color Emoji"',
      "serif":
        '"ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"',
      "mono":
        '"ui-monospace", "SDMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New"',
    },
  },
};
```

Logs:

```
[2:31:50 AM] Extension Name: sastan.twind-intellisense.
[2:31:50 AM] Extension Version: 0.2.1.
[2:31:50 AM] Using builtin twind
[2:31:50 AM] Extension is enabled. To disable, change the `twind.enable` setting to `false`.
[2:31:50 AM] Configuring @twind/typescript-plugin using: {
  "tags": [
    "tw",
    "apply"
  ],
  "attributes": [
    "tw",
    "class",
    "className"
  ],
  "styles": [
    "style",
    "styled"
  ],
  "debug": true,
  "enable": true
}
```

![image](https://user-images.githubusercontent.com/35933830/192173200-8b7e5624-1296-4c7d-8212-e0afa3e0754e.png)

**Comment by mooxl** [comment] 2022-09-29 07:36
it looks like it's a duplicate of: https://github.com/tw-in-js/vscode-twind-intellisense/issues/10

**Comment by rickyraz** [comment] 2022-09-29 10:03
i have read all of doc of twind for adding font from 'import' and 'font-face' it still doesn't work :(

**Comment by imjamesb** [comment] 2022-09-30 20:45
> it looks like it's a duplicate of: #10

Probably, there was not much info in #10 though.

**Comment by imjamesb** [comment] 2022-09-30 21:00
It works when removing the selfURL property.

**Comment by imjamesb** [comment] 2022-09-30 21:01
I think it has something to do with `import.` being used.

**Comment by imjamesb** [comment] 2022-09-30 21:05
Removing the `selfURL` property from the config file seems to solve the issue:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/35933830/193355966-83497d4c-6989-4f9e-a619-9e153b16bc59.png">

<img width="993" alt="image" src="https://user-images.githubusercontent.com/35933830/193356021-0091b0eb-4bc1-4ad6-b9e6-63b74d987e1c.png">

**Closed as completed** 2022-09-30 21:06 UTC

**Comment by mooxl** [comment] 2022-09-30 21:39
@imjamesb 

unfortunately still can't get it to work with the fix you mentioned above:

<details><summary>main.ts</summary><img width="997" alt="Screenshot 2022-09-30 at 23 30 51" src="https://user-images.githubusercontent.com/35741000/193359121-fd7e9ae3-0fea-4e27-a921-03b528db06d1.png"></details>

<details><summary>twind.config.ts</summary>
<img width="997" alt="Screenshot 2022-09-30 at 23 36 55" src="https://user-images.githubusercontent.com/35741000/193359599-f7e5c977-9519-4d31-8205-35c62c7919be.png">
</details>

Have also restarted both Twind Intellisense and Deno lsp.

**Comment by imjamesb** [comment] 2022-09-30 21:43
You cannot import `$fresh`

**Comment by imjamesb** [comment] 2022-09-30 21:44
Try changing it to

```ts
/** @type {import("$fresh").Options} */
```

Right above the export, so it avoids the import entirely.

**Comment by mooxl** [comment] 2022-09-30 22:05
Ok, weird.  
I tried your suggestion, but unfortunately it still didn't work. 
However, since I no longer use the `apply` function of Twind, Intellisense and also the linting works project-wide.

<img width="997" alt="Screenshot 2022-10-01 at 00 01 22" src="https://user-images.githubusercontent.com/35741000/193362711-7c8a4eec-6bca-4aa6-b8e6-a4d2075eecb4.png">

**Comment by imjamesb** [comment] 2022-09-30 22:07
You are still importing `$fresh`
<img width="473" alt="image" src="https://user-images.githubusercontent.com/35933830/193362902-97e11191-3370-4fa9-9146-47cfd776cc6c.png">

You cannot do that

**Comment by imjamesb** [comment] 2022-09-30 22:08
Change it to:

```ts
/** @type {Omit<import("$fresh/plugins/twind.ts").Options, "selfURL">} */
export default {
  // ...
```

**Comment by mooxl** [comment] 2022-09-30 22:50
As I said, I have already tried your suggestion:
<details><summary>With a type:</summary>
<img width="997" alt="Screenshot 2022-10-01 at 00 10 37" src="https://user-images.githubusercontent.com/35741000/193363393-745c3f9c-8fc8-4f8e-afb5-37bc338de0d8.png">
</details>

<details><summary>Without typing:</summary>
<img width="997" alt="Screenshot 2022-10-01 at 00 10 48" src="https://user-images.githubusercontent.com/35741000/193363463-c1098515-fe6e-49bd-8bf4-d137a87b3397.png">
</details>

Now that I define the preflight directly in the object, everything works:)
Thank you!

<img width="997" alt="Screenshot 2022-10-01 at 00 49 15" src="https://user-images.githubusercontent.com/35741000/193366458-df36faf7-088a-45aa-9ebc-4f5564006879.png">

**Comment by JuerGenie** [comment] 2022-10-03 08:50
May you could just trying remove fresh's import like `import {} from "$fresh"` cause is that extension cannot load config (cause module `$fresh` not found), so extension will use default config.
And if you import other things like `twind/colors`, run `npm install twind` first, when you reload intellisense, it will be work.
When extension load config, that will import config's dependencies from workspace's `node_modules` (or other source file that in workspace), see [loading module from node_modules](https://nodejs.org/dist/latest-v18.x/docs/api/modules.html#loading-from-node_modules-folders).

Hope this comment can help you 😄.

**Comment by gmunumel** [comment] 2022-10-03 10:58
Thanks @mooxl for showing your solution. Could you also shown your **twind.config.ts** file?

I'm using `twind` with `deno` and fresh version 1.1. 

```
deno 1.25.0 (release, x86_64-pc-windows-msvc)
v8 10.6.194.5
typescript 4.7.4
```

This is my **main.ts**:

```typescript
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />

import { start } from "$fresh/server.ts";
import manifest from "@/fresh.gen.ts";

import twindPlugin from "$fresh/plugins/twind.ts";
import twindConfig from "@/twind.config.ts";

await start(manifest, {
  plugins: [
    twindPlugin({
      selfURL: new URL("./twind.config.ts", import.meta.url).href,
      preflight: {},
      ...twindConfig,
    }),
  ],
});
```

**twind.config.ts**:

```typescript
import { Options } from "$fresh/plugins/twind.ts";
import * as colors from "twind/colors";

export default {
  // selfURL: import.meta.url,
  darkMode: "class",
  mode: "silent",
  theme: {
    extend: {
      colors,
    },
  },
} as unknown as Options;

```

I got this error in my **main.ts**: 

![Screenshot 1](https://user-images.githubusercontent.com/276168/193560761-b87d5021-0d40-4be3-9da2-43f215202fda.png)

![Screenshot 2](https://user-images.githubusercontent.com/276168/193560779-30ce9fc1-d459-49ab-9356-0bb8aef4c882.png)

The `bg-sky-800` rule should be define in colors: `import * as colors from "twind/colors";` in **twind.config.ts**.

**Comment by JuerGenie** [comment] 2022-10-03 11:25
> Thanks @mooxl for showing your solution. Could you also shown your **twind.config.ts** file?
> 
> I'm using `twind` with `deno` and fresh version 1.1.
> 
> ```
> deno 1.25.0 (release, x86_64-pc-windows-msvc)
> v8 10.6.194.5
> typescript 4.7.4
> ```
> 
> This is my **main.ts**:
> 
> ```ts
> /// <reference no-default-lib="true" />
> /// <reference lib="dom" />
> /// <reference lib="dom.iterable" />
> /// <reference lib="dom.asynciterable" />
> /// <reference lib="deno.ns" />
> 
> import { start } from "$fresh/server.ts";
> import manifest from "@/fresh.gen.ts";
> 
> import twindPlugin from "$fresh/plugins/twind.ts";
> import twindConfig from "@/twind.config.ts";
> 
> await start(manifest, {
>   plugins: [
>     twindPlugin({
>       selfURL: new URL("./twind.config.ts", import.meta.url).href,
>       preflight: {},
>       ...twindConfig,
>     }),
>   ],
> });
> ```
> 
> **twind.config.ts**:
> 
> ```ts
> import { Options } from "$fresh/plugins/twind.ts";
> import * as colors from "twind/colors";
> 
> export default {
>   // selfURL: import.meta.url,
>   darkMode: "class",
>   mode: "silent",
>   theme: {
>     extend: {
>       colors,
>     },
>   },
> } as unknown as Options;
> ```
> 
> I got this error in my **main.ts**:
> 
> ![Screenshot 1](https://user-images.githubusercontent.com/276168/193560761-b87d5021-0d40-4be3-9da2-43f215202fda.png)
> 
> ![Screenshot 2](https://user-images.githubusercontent.com/276168/193560779-30ce9fc1-d459-49ab-9356-0bb8aef4c882.png)
> 
> The `bg-sky-800` rule should be define in colors: `import * as colors from "twind/colors";` in **twind.config.ts**.

Hey, @gmunumel, the error means your `selfURL` will be overwritten by `...twindConfig` because typeof twindConfig is `Options`, `Options` has property `selfURL`.

Move `selfURL` to under of `...twindConfig` like:
```typescript
twindPlugin({
  preflight: {},
  ...twindConfig,
  selfURL: new URL("./twind.config.ts", import.meta.url).href,
});
```

Or you can change the twindConfig's type assert to `Omit<Options, "selfURL">`, it will be work too.

---

To fix the second error (`unknown utility "bg-sky-800"`), you could trying my [solution](https://github.com/tw-in-js/vscode-twind-intellisense/issues/18#issuecomment-1265129032). you cannot import `$fresh` and `twind/colors` in `twind.config.ts` when your `node_modules` haven't this two.

**Comment by mooxl** [comment] 2022-10-03 11:48
As @JuerGenie mentioned, you get an error because the typing is not right.
Here are my two files:

---
main.ts
```ts
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />

import { start } from "$fresh/server.ts";
import manifest from "./fresh.gen.ts";
import { apply } from "twind";

import twindPlugin from "$fresh/plugins/twind.ts";
import twindConfig from "./twind.config.ts";

await start(manifest, {
  plugins: [
    twindPlugin({
      selfURL: new URL("./twind.config.ts", import.meta.url).href,
      preflight: {
        "@font-face": [
          {
            fontFamily: "Plex",
            src: 'url(/fonts/Plex-Regular.woff2) format("woff2")',
          },
          {
            fontFamily: "Plex",
            fontWeight: "bold",
            src: 'url(/fonts/Plex-Bold.woff2) format("woff2")',
          },
        ],
        html: apply`text-html bg-gray`,
        body: apply`text-sm text-white font-plex leading-none tracking-wide`,
      },
      ...twindConfig,
    }),
  ],
});
```

---
twind.config.ts
```ts
import { Options } from "$fresh/plugins/twind.ts";
export default {
  theme: {
    fontSize: {
      html: "62.5%",
      sm: "1.6rem",
      md: "2.1rem",
      lg: "3rem",
      xl: "5rem",
    },
    fontWeight: {
      bold: "700",
    },
    screens: {
      lg: { max: "1040px" },
      md: { max: "768px" },
      sm: { max: "640px" },
    },
    fontFamily: {
      plex: ["Plex", "sans-serif"],
    },
    maxWidth: {
      xl: "1000px",
      experience: "550px",
    },
    extend: {
      colors: {
        gray: {
          DEFAULT: "#111111",
          light: "#888888",
          dark: "#222222",
        },
      },
      gridTemplateColumns: {
        desktop: "min-content auto",
      },
    },
  },
} as Pick<Options, "theme">;
```

With this structure i get no linting and typing errors and the intellisense from Twind works:) @gmunumel

**Comment by gmunumel** [comment] 2022-10-03 12:18
Thanks @JuerGenie and @mooxl, for your suggestions. Indeed the lint errors are gone. I only have the error with the custom css: `unknown utility "bg-sky-800"`. 

I tried to do the following with no luck (I'm using `deno` and not `node`, so not `npm_modules` folder):

**main.ts**:

```typescript
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />

import { start } from "$fresh/server.ts";
import manifest from "@/fresh.gen.ts";

import twindPlugin from "$fresh/plugins/twind.ts";
// import twindConfig from "@/twind.config.ts";
import * as colors from "twind/colors";

await start(manifest, {
  plugins: [
    twindPlugin({
      selfURL: new URL("./twind.config.ts", import.meta.url).href,
      preflight: {},
      // ...twindConfig,
      darkMode: "class",
      // mode: "silent",
      theme: {
        extend: {
          colors,
        },
      },
    }),
  ],
});

```

**import_map.json**:
```json
{
  "imports": {
    "@/": "./",
    "$fresh/": "https://deno.land/x/fresh@1.1.1/",
    "preact": "https://esm.sh/preact@10.11.0",
    "preact/": "https://esm.sh/preact@10.11.0/",
    "preact-render-to-string": "https://esm.sh/*preact-render-to-string@5.2.4",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.0.3",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.0.1",
    "twind": "https://esm.sh/twind@0.16.17",
    "twind/": "https://esm.sh/twind@0.16.17/",
    "dotenv": "https://deno.land/x/dotenv@v3.2.0/load.ts",
    "$std/": "https://deno.land/std@0.151.0/",
    "statery": "https://esm.sh/statery@0.5.4?alias=react:preact/compat&deps=preact@10.8.2",
    "jwt": "https://deno.land/x/djwt@v2.7/mod.ts"
  }
}

```


I don't want to hijack this topic. May I open another ticket if you want to ;)

**Comment by mooxl** [comment] 2022-10-03 12:26
You have to define your theme in `twind.config.ts` as show above. If you don't do that, twind doesn't recognise the custom `theme`. Don't ask me why🙃 @gmunumel

**Comment by gmunumel** [comment] 2022-10-03 12:34
Nop. Doesn't work for me. Still get the same error in my **index.tsx**.

**main.ts**:

```typescript
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />

import { start } from "$fresh/server.ts";
import manifest from "@/fresh.gen.ts";

import twindPlugin from "$fresh/plugins/twind.ts";
import twindConfig from "@/twind.config.ts";

await start(manifest, {
  plugins: [
    twindPlugin({
      selfURL: new URL("./twind.config.ts", import.meta.url).href,
      preflight: {},
      ...twindConfig,
    }),
  ],
});

```

**twind.config.ts**:

```typescript
// import { Options } from "$fresh/plugins/twind.ts";
import * as colors from "twind/colors";

export default {
  // selfURL: import.meta.url,
  darkMode: "class",
  mode: "silent",
  theme: {
    extend: {
      colors,
    },
  },
  // deno-lint-ignore no-explicit-any
} as Pick<any, "theme">;
```

**Comment by JuerGenie** [comment] 2022-10-03 12:34
> Thanks @JuerGenie and @mooxl, for your suggestions. Indeed the lint errors are gone. I only have the error with the custom css: `unknown utility "bg-sky-800"`.
> 
> I tried to do the following with no luck (I'm using `deno` and not `node`, so not `npm_modules` folder):
> 
> **main.ts**:
> 
> ```ts
> /// <reference no-default-lib="true" />
> /// <reference lib="dom" />
> /// <reference lib="dom.iterable" />
> /// <reference lib="dom.asynciterable" />
> /// <reference lib="deno.ns" />
> 
> import { start } from "$fresh/server.ts";
> import manifest from "@/fresh.gen.ts";
> 
> import twindPlugin from "$fresh/plugins/twind.ts";
> // import twindConfig from "@/twind.config.ts";
> import * as colors from "twind/colors";
> 
> await start(manifest, {
>   plugins: [
>     twindPlugin({
>       selfURL: new URL("./twind.config.ts", import.meta.url).href,
>       preflight: {},
>       // ...twindConfig,
>       darkMode: "class",
>       // mode: "silent",
>       theme: {
>         extend: {
>           colors,
>         },
>       },
>     }),
>   ],
> });
> ```
> 
> **import_map.json**:
> 
> ```json
> {
>   "imports": {
>     "@/": "./",
>     "$fresh/": "https://deno.land/x/fresh@1.1.1/",
>     "preact": "https://esm.sh/preact@10.11.0",
>     "preact/": "https://esm.sh/preact@10.11.0/",
>     "preact-render-to-string": "https://esm.sh/*preact-render-to-string@5.2.4",
>     "@preact/signals": "https://esm.sh/*@preact/signals@1.0.3",
>     "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.0.1",
>     "twind": "https://esm.sh/twind@0.16.17",
>     "twind/": "https://esm.sh/twind@0.16.17/",
>     "dotenv": "https://deno.land/x/dotenv@v3.2.0/load.ts",
>     "$std/": "https://deno.land/std@0.151.0/",
>     "statery": "https://esm.sh/statery@0.5.4?alias=react:preact/compat&deps=preact@10.8.2",
>     "jwt": "https://deno.land/x/djwt@v2.7/mod.ts"
>   }
> }
> ```
> 
> I don't want to hijack this topic. May I open another ticket if you want to ;)

It's ok, I'm using Deno too, but extension with VSCode was running on electron (based on NodeJS), so you know :D

**Comment by CyanFroste** [comment] 2022-10-08 11:21
Workaround -> https://github.com/tw-in-js/vscode-twind-intellisense/issues/10#issuecomment-1272295973

This will let you use the official tailwind extension instead

**Comment by pandasoli** [comment] 2022-11-09 00:39
I had the same problem and put `/** @type {Omit<import("$fresh/plugins/twind.ts").Options, "selfURL">} */` in `twind.config.ts` helped me.

but the error keeps in the rest of the files.  
how can I fix it?

`twind.config.ts`
![image](https://user-images.githubusercontent.com/76575902/200707279-b27aad8c-3b72-41e0-8d4e-b465dc94a98d.png)

`main.ts`
![image](https://user-images.githubusercontent.com/76575902/200707346-6a59028c-fd5b-4fce-81f8-6d316295b7f1.png)

Some component
![image](https://user-images.githubusercontent.com/76575902/200708144-d4cb9d85-86dc-4418-9a8e-e0e8cd80afba.png)e8e7a5280446.png)

**Comment by pandasoli** [comment] 2022-11-09 00:44
I had the same problem and put `/** @type {Omit<import("$fresh/plugins/twind.ts").Options, "selfURL">} */` in `twind.config.ts` helped me.

but the error keeps in the rest of the files.  
how can I fix it?

`twind.config.ts`
![image](https://user-images.githubusercontent.com/76575902/200708465-4c7ec5dc-30ec-4988-aa65-ad9871bfcfdf.png)

`main.ts`
![image](https://user-images.githubusercontent.com/76575902/200707346-6a59028c-fd5b-4fce-81f8-6d316295b7f1.png)

Some component
![image](https://user-images.githubusercontent.com/76575902/200708144-d4cb9d85-86dc-4418-9a8e-e0e8cd80afba.png)
